#!/usr/bin/env bash
# Installs, configures, and starts the server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

# Create index file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Create default Nginx configuration file
sudo mkdir -p /etc/nginx/sites-enabled/
sudo touch /etc/nginx/sites-enabled/default

SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ http://www.redirectedpage.com;
        }
}"

sudo bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

# Create Nginx configuration file
sudo touch /etc/nginx/nginx.conf

# Add a custom header to Nginx config
HOSTNAME=$(hostname)
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

# Start or restart Nginx service
if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo service nginx start
else
    sudo service nginx restart
fi
