#!/usr/bin/env bash
# Install HAproxy
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAproxy
sudo tee -a /etc/haproxy/haproxy.cfg << EOF
frontend http-in
    bind *:80
    mode http
    default_backend servers

backend servers
    mode http
    balance roundrobin
    server 184216-web-01 54.152.59.204 check port 80
    server 184216-web-02 54.242.109.112 check port 80
EOF

# Restart HAproxy service
sudo systemctl enable haproxy
sudo systemctl restart haproxy
